test: improve integration test workflow (#512)

diff --git a/.github/workflows/int_test.yml b/.github/workflows/int_test.yml
--- a/.github/workflows/int_test.yml
+++ b/.github/workflows/int_test.yml
@@ -96,18 +96,40 @@ env:
   RUNTIME_CREATE_ARGS: "${{ inputs.runtime-create-args }}"
   RUNTIME_INIT_ARGS: "${{ inputs.runtime-init-args }}"
 
+
 jobs:
+  setup:
+    name: "Check Inputs"
+    runs-on: ubuntu-22.04
+    outputs:
+      create_args: ${{ steps.custom_input.outputs.CREATE_ARG }}
+      init_args: ${{ steps.custom_input.outputs.INIT_ARG }}
+    steps:
+      - name: "Check Keep On Failure arg"
+        run: |
+          if [[ ! ${{ env.KEEP_ALIVE }} =~ ^[0-9]+$ ]]; then
+            echo "The keep alive input is not a valid number"
+            exit 1
+          fi
+      - name: "Output custom inputs for future job"
+        id: custom_input
+        run: |
+          echo "CREATE_ARG=${{ env.RUNTIME_CREATE_ARGS }}" >> $GITHUB_OUTPUT
+          echo "INIT_ARG=${{ env.RUNTIME_INIT_ARGS }}" >> $GITHUB_OUTPUT
   test:
+    needs: setup
     env:
       CLUSTER_NAME: "opt${{ github.run_number }}${{ matrix.feature }}"
       INSTANCE_NAME: "inst${{ github.run_number }}${{ matrix.feature }}"
       KEYVAULT_NAME: "kv${{ github.run_number }}"
+      INIT_ARG: ${{ needs.setup.outputs.init_args }}
+      CREATE_ARG: ${{ needs.setup.outputs.create_args }}
     strategy:
       fail-fast: false
       matrix:
         feature: [custom-input, default, insecure-listener, syncrules, redeploy, trustbundle]
         runtime-args:
-          - ${{ inputs.runtime-create-args != '' || inputs.runtime-init-args != '' }}
+          - ${{ needs.setup.outputs.init_args != '' || needs.setup.outputs.create_args != '' }}
         exclude:
           - feature: custom-input
             runtime-args: false
@@ -124,12 +146,6 @@ jobs:
     name: "Run cluster tests"
     runs-on: ubuntu-22.04
     steps:
-      - name: "Check Keep On Failure arg"
-        run: |
-          if [[ ! ${{ env.KEEP_ALIVE }} =~ ^[0-9]+$ ]]; then
-            echo "The input is not a valid number"
-            exit 1
-          fi
       - name: "Determine Init Args"
         id: "init"
         run: |
@@ -370,15 +386,22 @@ jobs:
       - name: "Keep cluster alive"
         if: ${{ env.KEEP_ALIVE > 0 && failure() }}
         run: |
+          kubectl create clusterrolebinding teamaccessbinding --clusterrole cluster-admin --group ${{ secrets.CLUSTER_ACCESS_SG }} >/dev/null 2>&1
+
+          echo "Cluster ${{ env.CLUSTER_NAME }} in resource group ${{ env.RESOURCE_GROUP }}"
+          echo "Instance name ${{ env.INSTANCE_NAME }}"
+          echo ""
+
+          echo "Please ensure you have the required roles: \"Azure Arc Kubernetes Viewer\" and \"Azure Arc Enabled Kubernetes Cluster User Role\""
+          echo "To connect to the cluster please use"
+          echo "az connectedk8s proxy -g ${{ env.RESOURCE_GROUP }} -n ${{ env.CLUSTER_NAME }}"
+          echo ""
+
           TIME_LIMIT=${{ env.KEEP_ALIVE }}
           if (( $TIME_LIMIT > 240 )); then
             echo "Given time limit is over the maximum of 4 hours. Setting to 4 hours."
             TIME_LIMIT=240
           fi
-
-          echo "Cluster ${{ env.CLUSTER_NAME }} in resource group ${{ env.RESOURCE_GROUP }}"
-          echo "Instance name ${{ env.INSTANCE_NAME }}"
-          echo ""
 
           for ((i=0; i < $TIME_LIMIT; i+=1)); do
             if [ $(( i % 10 )) == 0 ]; then
